const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

function ensurePdfDir() {
  const dir = path.join(__dirname, '../../public/pdfs');
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  return dir;
}

function formatDate(dateStr) {
  // Parse as UTC to avoid local-timezone off-by-one on day names/numbers
  const s = typeof dateStr === 'string' ? dateStr : dateStr.toISOString().split('T')[0];
  const [year, month, day] = s.split('-').map(Number);
  const d = new Date(Date.UTC(year, month - 1, day));
  const days = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
  const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
  return `${days[d.getUTCDay()]}, ${d.getUTCDate()} ${months[d.getUTCMonth()]}`;
}

function drawHeader(doc, subtitle) {
  doc.rect(0, 0, doc.page.width, 75).fill('#16a34a');
  doc.fill('white').fontSize(22).font('Helvetica-Bold').text('CookConnect', 50, 18);
  doc.fontSize(11).font('Helvetica').text(subtitle, 50, 48);
  doc.y = 95;
}

function drawDivider(doc, color = '#e5e7eb') {
  doc.moveTo(50, doc.y).lineTo(doc.page.width - 50, doc.y).strokeColor(color).stroke();
  doc.moveDown(0.4);
}

async function generateWeeklyPDF(user, planDays, familyCount = 1) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const dir = ensurePdfDir();
    const filename = `weekly-plan-${user.id}-${Date.now()}.pdf`;
    const filepath = path.join(dir, filename);
    const stream = fs.createWriteStream(filepath);
    doc.pipe(stream);

    const sorted = [...planDays].sort((a, b) => a.day_number - b.day_number).slice(0, 7);
    const startDate = sorted[0] ? formatDate(sorted[0].day_date) : '';
    const endDate = sorted[sorted.length - 1] ? formatDate(sorted[sorted.length - 1].day_date) : '';

    drawHeader(doc, 'Weekly Meal Plan');

    doc.fill('#1f2937').fontSize(13).font('Helvetica-Bold')
      .text(`Family: ${user.family_name || user.name}`);
    doc.fill('#6b7280').fontSize(10).font('Helvetica')
      .text(`Period: ${startDate} — ${endDate}  ·  ${familyCount} member${familyCount !== 1 ? 's' : ''}`);
    doc.moveDown(0.6);
    drawDivider(doc);

    function getWeeklyMealItems(day, mealType) {
      const fromMealItems = (day.mealItems || [])
        .filter(mi => mi.meal_type === mealType && mi.menuItem)
        .map(mi => mi.menuItem);
      if (fromMealItems.length > 0) return fromMealItems;
      if (mealType === 'breakfast' && day.breakfast) return [day.breakfast];
      if (mealType === 'lunch' && day.lunch) return [day.lunch];
      if (mealType === 'dinner' && day.dinner) return [day.dinner];
      return [];
    }

    sorted.forEach(day => {
      if (doc.y > 660) { doc.addPage(); doc.y = 50; }

      const bItems = getWeeklyMealItems(day, 'breakfast');
      const lItems = getWeeklyMealItems(day, 'lunch');
      const dItems = getWeeklyMealItems(day, 'dinner');

      const sumCal = items => items.reduce((s, i) => s + (i.calories_per_serving || 0), 0) * familyCount;
      const bCal = sumCal(bItems), lCal = sumCal(lItems), dCal = sumCal(dItems);
      const totalCal = bCal + lCal + dCal;

      const nameList = items => items.length ? items.map(i => i.name).join(', ') : '—';

      // Day heading
      doc.fill('#16a34a').fontSize(11).font('Helvetica-Bold').text(formatDate(day.day_date));
      doc.moveDown(0.2);

      const col1 = 50, col2 = 140, col3 = 390;
      const rowH = 16;
      const startY = doc.y;

      doc.fill('#6b7280').fontSize(9).font('Helvetica-Bold');
      doc.text('Breakfast', col1, startY);
      doc.text(nameList(bItems), col2, startY, { width: 240 });
      doc.text(`${bCal} cal`, col3, startY);

      doc.text('Lunch', col1, startY + rowH);
      doc.text(nameList(lItems), col2, startY + rowH, { width: 240 });
      doc.text(`${lCal} cal`, col3, startY + rowH);

      doc.text('Dinner', col1, startY + rowH * 2);
      doc.text(nameList(dItems), col2, startY + rowH * 2, { width: 240 });
      doc.text(`${dCal} cal`, col3, startY + rowH * 2);

      doc.fill('#059669').fontSize(9).font('Helvetica-Bold')
        .text(`Total: ${totalCal} kcal`, col3, startY + rowH * 3);

      doc.y = startY + rowH * 4 + 6;
      drawDivider(doc, '#f3f4f6');
    });

    doc.moveDown(0.5);
    doc.fill('#9ca3af').fontSize(8).font('Helvetica')
      .text(
        `Generated by CookConnect · ${new Date().toLocaleDateString('en-IN')} · BF 7:30AM | LU 12:30PM | DI 7:30PM`,
        { align: 'center' }
      );

    doc.end();
    stream.on('finish', () => resolve({ filename, filepath }));
    stream.on('error', reject);
  });
}

async function generateTodayPDF(user, planDay, familyCount = 1) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const dir = ensurePdfDir();
    const filename = `today-menu-${user.id}-${Date.now()}.pdf`;
    const filepath = path.join(dir, filename);
    const stream = fs.createWriteStream(filepath);
    doc.pipe(stream);

    drawHeader(doc, "Today's Menu");

    doc.fill('#1f2937').fontSize(13).font('Helvetica-Bold')
      .text(`Family: ${user.family_name || user.name}`);
    if (planDay) {
      doc.fill('#6b7280').fontSize(10).font('Helvetica')
        .text(`Date: ${formatDate(planDay.day_date)}  ·  ${familyCount} member${familyCount !== 1 ? 's' : ''}`);
    }
    doc.moveDown(0.6);
    drawDivider(doc);

    if (!planDay) {
      doc.fill('#6b7280').fontSize(12).text('No meal plan found for today.', { align: 'center' });
    } else {
      // Resolve items per meal: prefer mealItems array, fall back to legacy single fields
      function getMealItems(day, mealType) {
        const fromMealItems = (day.mealItems || [])
          .filter(mi => mi.meal_type === mealType && mi.menuItem)
          .map(mi => mi.menuItem);
        if (fromMealItems.length > 0) return fromMealItems;
        if (mealType === 'breakfast' && day.breakfast) return [day.breakfast];
        if (mealType === 'lunch' && day.lunch) return [day.lunch];
        if (mealType === 'dinner' && day.dinner) return [day.dinner];
        return [];
      }

      const meals = [
        { label: 'Breakfast', time: '7:30 AM', mealType: 'breakfast', color: '#f97316' },
        { label: 'Lunch', time: '12:30 PM', mealType: 'lunch', color: '#3b82f6' },
        { label: 'Dinner', time: '7:30 PM', mealType: 'dinner', color: '#8b5cf6' }
      ];

      let totalCal = 0;

      meals.forEach(meal => {
        if (doc.y > 660) { doc.addPage(); doc.y = 50; }

        const items = getMealItems(planDay, meal.mealType);

        doc.fill(meal.color).fontSize(13).font('Helvetica-Bold')
          .text(`${meal.label}  ·  ${meal.time}`);
        doc.moveDown(0.2);

        if (items.length > 0) {
          items.forEach(item => {
            const prep = (item.prep_time_minutes || 0) + (item.cook_time_minutes || 0);
            const calPer = item.calories_per_serving || 0;
            const calTotal = calPer * familyCount;
            totalCal += calTotal;
            doc.fill('#1f2937').fontSize(11).font('Helvetica-Bold').text(`• ${item.name}`);
            let meta = `  ${item.cuisine_type || ''}  ·  ${calTotal} kcal (${familyCount} members)`;
            if (familyCount > 1) meta += `  ·  ${calPer} kcal/person`;
            if (prep > 0) meta += `  ·  ${prep} min prep`;
            doc.fill('#6b7280').fontSize(9).font('Helvetica').text(meta);
            if (item.protein_g || item.carbs_g || item.fat_g) {
              const p = Math.round((item.protein_g || 0) * familyCount);
              const c = Math.round((item.carbs_g || 0) * familyCount);
              const f = Math.round((item.fat_g || 0) * familyCount);
              doc.fill('#9ca3af').fontSize(8)
                .text(`  P: ${p}g  C: ${c}g  F: ${f}g  (for ${familyCount})`);
            }
          });
        } else {
          doc.fill('#9ca3af').fontSize(10).font('Helvetica').text('Not planned');
        }

        doc.moveDown(0.6);
        drawDivider(doc, '#f3f4f6');
      });

      if (!totalCal) totalCal = planDay.total_calories || 0;

      doc.moveDown(0.3);
      doc.fill('#16a34a').fontSize(13).font('Helvetica-Bold')
        .text(`Total Day Calories: ${totalCal} kcal`, { align: 'center' });
    }

    doc.moveDown(2);
    doc.fill('#9ca3af').fontSize(8).font('Helvetica')
      .text(`Generated by CookConnect · ${new Date().toLocaleDateString('en-IN')}`, { align: 'center' });

    doc.end();
    stream.on('finish', () => resolve({ filename, filepath }));
    stream.on('error', reject);
  });
}

// ── Shopping List helpers ──────────────────────────────────────────────────────

// ml per 1 unit of each volume measure
const VOLUME_TO_ML = {
  cup: 240, cups: 240,
  tbsp: 15, tablespoon: 15, tablespoons: 15,
  tsp: 5, teaspoon: 5, teaspoons: 5,
  'fl oz': 30, 'fluid ounce': 30, 'fluid ounces': 30,
  pint: 473, pints: 473,
  quart: 946, quarts: 946,
  litre: 1000, liter: 1000, litres: 1000, liters: 1000, l: 1000,
  ml: 1, milliliter: 1, milliliters: 1, millilitre: 1, millilitres: 1,
};

// grams per 1 cup for common dry/semi-dry ingredients (Indian + general)
const G_PER_CUP = {
  rice: 185, 'basmati rice': 185, 'brown rice': 185,
  flour: 120, 'wheat flour': 120, atta: 120, maida: 110, besan: 92, 'gram flour': 92,
  sugar: 200, 'powdered sugar': 120, 'icing sugar': 120, 'brown sugar': 220,
  salt: 292,
  oats: 90,
  dal: 190, lentils: 190, 'chana dal': 200, 'moong dal': 210, 'urad dal': 210,
  'toor dal': 200, 'masoor dal': 190,
  chickpeas: 200, 'chana': 200, 'rajma': 190, 'kidney beans': 190,
  paneer: 250,
  poha: 80, 'flattened rice': 80,
  semolina: 167, suji: 167, rava: 167, sooji: 167,
  'rolled oats': 90,
  cornmeal: 156,
  quinoa: 170,
  millet: 200,
  sago: 160, sabudana: 160,
  coconut: 80, 'desiccated coconut': 80,
  breadcrumbs: 108,
};

// Convert a quantity+unit to metric { qty, unit }
function toMetric(qty, unit, ingredientName) {
  const u = (unit || '').toLowerCase().trim();
  const name = (ingredientName || '').toLowerCase().trim();

  const mlFactor = VOLUME_TO_ML[u];
  if (!mlFactor) return { qty, unit }; // already g / kg / piece / or unknown — leave as-is

  const totalMl = qty * mlFactor;

  // Try density lookup: check ingredient name against known keys
  for (const [key, gPerCup] of Object.entries(G_PER_CUP)) {
    if (name.includes(key)) {
      const grams = Math.round((totalMl / 240) * gPerCup);
      return { qty: grams, unit: 'g' };
    }
  }

  // No density found — return as ml (or L if large)
  if (totalMl >= 1000) return { qty: parseFloat((totalMl / 1000).toFixed(2)), unit: 'L' };
  return { qty: Math.round(totalMl), unit: 'ml' };
}

function parseQty(str) {
  if (!str) return null;
  const s = str.trim();
  // Mixed: "1 1/2"
  const mixed = s.match(/^(\d+)\s+(\d+)\/(\d+)/);
  if (mixed) return parseInt(mixed[1]) + parseInt(mixed[2]) / parseInt(mixed[3]);
  // Fraction: "1/2"
  const frac = s.match(/^(\d+)\/(\d+)/);
  if (frac) return parseInt(frac[1]) / parseInt(frac[2]);
  // Plain number or decimal
  const num = s.match(/^(\d+\.?\d*)/);
  if (num) return parseFloat(num[1]);
  return null;
}

function extractUnit(str) {
  if (!str) return '';
  return str.trim().replace(/^[\d\s\/\.]+/, '').trim();
}

function formatQty(num, unit) {
  // Metric units — just show the number cleanly
  const metricUnits = ['g', 'kg', 'ml', 'l', 'L'];
  if (unit && metricUnits.includes(unit)) {
    return Number.isInteger(num) ? String(num) : num.toFixed(1);
  }
  // Non-metric — keep fraction symbols for readability
  if (Number.isInteger(num)) return String(num);
  const frac = num - Math.floor(num);
  const whole = Math.floor(num);
  const fracs = { 0.25: '¼', 0.5: '½', 0.75: '¾', 0.33: '⅓', 0.67: '⅔' };
  const nearest = Object.keys(fracs).reduce((a, b) => Math.abs(b - frac) < Math.abs(a - frac) ? b : a);
  if (Math.abs(frac - nearest) < 0.05) {
    return whole > 0 ? `${whole} ${fracs[nearest]}` : fracs[nearest];
  }
  return num.toFixed(1);
}

function consolidateIngredients(planDays, familyCount) {
  const map = new Map(); // key: lowercase name

  planDays.forEach(day => {
    // Prefer mealItems array; fall back to legacy single fields
    let mealItemsList = (day.mealItems || []).map(mi => mi.menuItem).filter(Boolean);
    if (mealItemsList.length === 0) {
      mealItemsList = [day.breakfast, day.lunch, day.dinner].filter(Boolean);
    }
    const meals = mealItemsList;
    meals.forEach(meal => {
      if (!meal.ingredients || !meal.ingredients.length) return;
      meal.ingredients.forEach(ing => {
        const key = ing.name.toLowerCase().trim();
        const rawUnit = ing.unit || extractUnit(ing.quantity) || '';
        const num = parseQty(ing.quantity);

        if (!map.has(key)) {
          map.set(key, { name: ing.name, unit: rawUnit, total: null, unparsed: [], notes: ing.notes || '' });
        }
        const entry = map.get(key);

        if (num !== null) {
          // Convert to metric before accumulating
          const { qty: metricQty, unit: metricUnit } = toMetric(num * familyCount, rawUnit, ing.name);
          if (entry.total === null) {
            entry.total = metricQty;
            entry.unit = metricUnit;
          } else {
            entry.total += metricQty;
            // If units differ after conversion (shouldn't happen for same ingredient), keep existing
          }
        } else {
          entry.unparsed.push(`${ing.quantity}${rawUnit ? ' ' + rawUnit : ''} ×${familyCount}`);
        }
      });
    });
  });

  return Array.from(map.values()).sort((a, b) => a.name.localeCompare(b.name));
}

async function generateShoppingListPDF(user, planDays, familyCount) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const dir = ensurePdfDir();
    const filename = `shopping-list-${user.id}-${Date.now()}.pdf`;
    const filepath = path.join(dir, filename);
    const stream = fs.createWriteStream(filepath);
    doc.pipe(stream);

    const sorted = [...planDays].sort((a, b) => a.day_number - b.day_number).slice(0, 7);
    const startDate = sorted[0] ? formatDate(sorted[0].day_date) : '';
    const endDate = sorted[sorted.length - 1] ? formatDate(sorted[sorted.length - 1].day_date) : '';
    const items = consolidateIngredients(sorted, familyCount);

    // Header
    doc.rect(0, 0, doc.page.width, 75).fill('#0ea5e9');
    doc.fill('white').fontSize(22).font('Helvetica-Bold').text('CookConnect', 50, 18);
    doc.fontSize(11).font('Helvetica').text('Weekly Shopping List', 50, 48);
    doc.y = 95;

    doc.fill('#1f2937').fontSize(13).font('Helvetica-Bold')
      .text(`Family: ${user.family_name || user.name}`);
    doc.fill('#6b7280').fontSize(10).font('Helvetica')
      .text(`Week: ${startDate} — ${endDate}  ·  ${familyCount} member${familyCount !== 1 ? 's' : ''}`);
    doc.moveDown(0.5);
    doc.moveTo(50, doc.y).lineTo(doc.page.width - 50, doc.y).strokeColor('#e5e7eb').stroke();
    doc.moveDown(0.5);

    if (items.length === 0) {
      doc.fill('#6b7280').fontSize(11).text('No ingredients found in this plan.', { align: 'center' });
    } else {
      // Column headers
      const col1 = 50, col2 = 300, col3 = 430;
      doc.fill('#6b7280').fontSize(9).font('Helvetica-Bold');
      doc.text('INGREDIENT', col1, doc.y);
      doc.text('QUANTITY', col2, doc.y - doc.currentLineHeight());
      doc.text('NOTES', col3, doc.y - doc.currentLineHeight());
      doc.moveDown(0.2);
      doc.moveTo(50, doc.y).lineTo(doc.page.width - 50, doc.y).strokeColor('#d1d5db').stroke();
      doc.moveDown(0.3);

      items.forEach((item, i) => {
        if (doc.y > 750) { doc.addPage(); doc.y = 50; }

        const rowY = doc.y;
        const bg = i % 2 === 0 ? '#f9fafb' : '#ffffff';
        doc.rect(48, rowY - 2, doc.page.width - 96, 18).fill(bg);

        // Quantity display
        let qtyStr = '';
        if (item.total !== null) {
          qtyStr = `${formatQty(item.total, item.unit)} ${item.unit}`.trim();
        } else if (item.unparsed.length) {
          qtyStr = item.unparsed.join(', ');
        } else {
          qtyStr = 'as needed';
        }

        doc.fill('#1f2937').fontSize(10).font('Helvetica').text(item.name, col1, rowY, { width: 240 });
        doc.fill('#0ea5e9').font('Helvetica-Bold').text(qtyStr, col2, rowY, { width: 120 });
        doc.fill('#9ca3af').font('Helvetica').fontSize(9).text(item.notes || '', col3, rowY, { width: 110 });

        doc.y = rowY + 18;
      });
    }

    doc.moveDown(1.5);
    doc.moveTo(50, doc.y).lineTo(doc.page.width - 50, doc.y).strokeColor('#e5e7eb').stroke();
    doc.moveDown(0.5);
    doc.fill('#9ca3af').fontSize(8).font('Helvetica')
      .text(
        `Generated by CookConnect · ${new Date().toLocaleDateString('en-IN')} · Quantities for ${familyCount} member${familyCount !== 1 ? 's' : ''}`,
        { align: 'center' }
      );

    doc.end();
    stream.on('finish', () => resolve({ filename, filepath }));
    stream.on('error', reject);
  });
}

module.exports = { generateWeeklyPDF, generateTodayPDF, generateShoppingListPDF };
